export const errorCodeList = {
  2011: { msg: 'Please reapply for payment again.' },
  2070: { msg: 'Please reapply for payment again.' },
  2080: { msg: 'Please reapply for payment again.' },
  2081: { msg: 'Please reapply for payment again.' },
  2090: { msg: 'Payment cannot be continued due to system reasons.' },
  2130: { msg: 'Please reapply for payment again.' },
  2140: { msg: 'Please enter your email address.' },
  2150: { msg: 'Please try again.' },
  2160: { msg: 'Please select a legal currency.' },
  2170: { msg: 'Please confirm the payment amount you entered.' },
  2180: { msg: 'Please try again.' },
  2190: { msg: 'Please try again.' },
  2280: { msg: 'Please try again.' },
  2330: { msg: 'Please reapply for payment again.' },
  2340: { msg: 'No currency is selected.' },
  2341: { msg: 'Please select the currency again.' },
  2350: { msg: 'Please reinput the amount.' },
  2510: { msg: 'Please try again.' },
  2511: { msg: 'Invalid Payment URL.' },
  3020: { msg: 'The domain value is invalid.' },
  3030: { msg: 'Please enter the success notification URL in the correct format.' },
  3031: { msg: 'Please enter the successful payment return URL in the correct format.' },
  3032: { msg: 'Please enter the payment faliure return URL in the correct format.' },
  3080: { msg: 'Status is incorrect.' },
  3100: { msg: 'The number of items per page setting is incorrect.' },
  3101: { msg: 'The page number setting for the current page is incorrect.' },
  3110: { msg: 'Sort items are incorrect.' },
  3111: { msg: 'Sort settings are incorrect.' },
  3250: { msg: 'Please enter the exchange margin rate in the correct format.' },
  3430: { msg: 'Please enter the note in the correct format.' },
  3440: { msg: 'Please enter the note in 255 characters.' },
  3510: { msg: 'Invalid Merchant Id.' },
  3520: { msg: 'Invalid authorization code.' },
  3610: { msg: 'Invalid Merchant Id.' },
  3620: { msg: 'Note too long.' },
  3710: { msg: 'Invalid authorization code Id.' },
  3720: { msg: 'Note too long.' },
  3810: { msg: 'Invalid authorization code Id.' },
  3820: { msg: 'Invalid active value.' },
  3910: { msg: 'Invalid authorization code Id.' },
  9000: { msg: 'Cannot be continued due to system reasons.' }
}