import { PRODUCTION, DEVELOPMENT } from './modules/environment'
import { API_BASE_URL } from './modules/api'
import { LOGIN_TOKEN } from './modules/admin'
import {
  NORMAL_TYPE_PAYMENT,
  INVOICE_TYPE_PAYMENT,
  STATUS_PUBLISHED,
  STATUS_PROCESSING,
  STATUS_RESULT_FAILURE,
  STATUS_RESULT_SUCCESS
} from './modules/payment'
import { METAMASK, WALLET_CONNECT } from './modules/provider'
import { DARK_THEME, LIGHT_THEME } from './modules/color_theme'
import { NETWORKS } from './modules/network'
import { CURRENCIES } from './modules/currency'
import { HTTP_CODES } from './modules/http_code'
import { SAFE_THE_CHILDREN, UNICEF } from './modules/donation'
import {
  DEFAULT_SCAN_BLOCK_NUMBER_LIMIT,
  ETEHREUM_MAINNET_SCAN_BLOCK_NUMBER_LIMIT,
  ETEHREUM_GOERLI_SCAN_BLOCK_NUMBER_LIMIT,
  BSC_MAINNET_SCAN_BLOCK_NUMBER_LIMIT,
  BSC_TESTNET_SCAN_BLOCK_NUMBER_LIMIT,
  MATIC_MAINNET_SCAN_BLOCK_NUMBER_LIMIT,
  MATIC_TESTNET_SCAN_BLOCK_NUMBER_LIMIT,
  AVALANCHE_MAINNET_SCAN_BLOCK_NUMBER_LIMIT,
  AVALANCHE_TESTNET_SCAN_BLOCK_NUMBER_LIMIT
} from './modules/scan_block_number_limit'

export { PRODUCTION, DEVELOPMENT }
export { API_BASE_URL }
export { LOGIN_TOKEN }
export {
  NORMAL_TYPE_PAYMENT,
  INVOICE_TYPE_PAYMENT,
  STATUS_PUBLISHED,
  STATUS_PROCESSING,
  STATUS_RESULT_FAILURE,
  STATUS_RESULT_SUCCESS
}
export { METAMASK, WALLET_CONNECT }
export { DARK_THEME, LIGHT_THEME }
export { NETWORKS }
export { CURRENCIES }
export { HTTP_CODES }
export { SAFE_THE_CHILDREN, UNICEF }
export {
  DEFAULT_SCAN_BLOCK_NUMBER_LIMIT,
  ETEHREUM_MAINNET_SCAN_BLOCK_NUMBER_LIMIT,
  ETEHREUM_GOERLI_SCAN_BLOCK_NUMBER_LIMIT,
  BSC_MAINNET_SCAN_BLOCK_NUMBER_LIMIT,
  BSC_TESTNET_SCAN_BLOCK_NUMBER_LIMIT,
  MATIC_MAINNET_SCAN_BLOCK_NUMBER_LIMIT,
  MATIC_TESTNET_SCAN_BLOCK_NUMBER_LIMIT,
  AVALANCHE_MAINNET_SCAN_BLOCK_NUMBER_LIMIT,
  AVALANCHE_TESTNET_SCAN_BLOCK_NUMBER_LIMIT
}
