export default {
  abi: [
    {
      inputs: [
        { internalType: "address", name: "sharedProperty_", type: "address" },
        { internalType: "address", name: "slashCore_", type: "address" },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "previousOwner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "newOwner",
          type: "address",
        },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      inputs: [],
      name: "_sharedProperty",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "_slashCore",
      outputs: [
        { internalType: "contract ISlashCore", name: "", type: "address" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "payingToken_", type: "address" },
        { internalType: "uint256", name: "amountOut_", type: "uint256" },
        { internalType: "address[]", name: "path_", type: "address[]" },
        { internalType: "bytes", name: "reserved_", type: "bytes" },
      ],
      name: "getAmountIn",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "payingToken_", type: "address" },
        { internalType: "uint256", name: "amountIn_", type: "uint256" },
        { internalType: "address[]", name: "path_", type: "address[]" },
        { internalType: "bytes", name: "reserved_", type: "bytes" },
      ],
      name: "getAmountOut",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "account_", type: "address" },
        { internalType: "uint256", name: "amountOut_", type: "uint256" },
        { internalType: "address[]", name: "feePath_", type: "address[]" },
        { internalType: "bytes", name: "reserved_", type: "bytes" },
      ],
      name: "getFeeAmount",
      outputs: [
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "getSharedProperty",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "getSlashCore",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_tokenAddress", type: "address" },
        { internalType: "uint256", name: "_tokenAmount", type: "uint256" },
      ],
      name: "recoverWrongTokens",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "renounceOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "account_", type: "address" },
        { internalType: "address", name: "payingToken_", type: "address" },
        { internalType: "uint256", name: "amountIn_", type: "uint256" },
        {
          internalType: "uint256",
          name: "requiredAmountOut_",
          type: "uint256",
        },
        { internalType: "address[]", name: "path_", type: "address[]" },
        { internalType: "address[]", name: "feePath_", type: "address[]" },
        { internalType: "bytes", name: "reserved_", type: "bytes" },
      ],
      name: "submitTransaction",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "sharedProperty_", type: "address" },
        { internalType: "address", name: "slashCore_", type: "address" },
      ],
      name: "updateCoreAndSharedProperty",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ],
};
